# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 22:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='The key will be used to reference this campaign from your scripts.', unique=True, verbose_name='key')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('subject', models.CharField(help_text='May contain template variables.', max_length=255, verbose_name='e-mail subject')),
                ('prefix_subject', models.BooleanField(default=True, help_text='Wheter to prefix the subject with "None" or not.', verbose_name='prefix subject')),
                ('is_enabled', models.BooleanField(default=True, help_text="E-mails won't be sent for campaigns that are not enabled. Even if a script requests for sending. This is a way to turn off some campaigns temporarily without changing the source code.", verbose_name='enabled')),
                ('from_email', models.CharField(blank=True, help_text='Leave blank to use default (webmaster@localhost).', max_length=255, verbose_name='sender email')),
                ('template_file', models.FileField(upload_to='mailing/templates', verbose_name='template file')),
            ],
            options={
                'verbose_name_plural': 'e-mail campaigns',
                'verbose_name': 'e-mail campaign',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CampaignMailHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=70, verbose_name='name')),
                ('value', models.TextField(validators=[django.core.validators.MaxLengthValidator(998)], verbose_name='value')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_headers', to='mailing.Campaign')),
            ],
            options={
                'verbose_name_plural': 'additional headers',
                'verbose_name': 'additional header',
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Sent'), (3, 'Canceled'), (4, 'Failure')], default=1, verbose_name='status')),
                ('scheduled_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='scheduled on')),
                ('sent_on', models.DateTimeField(blank=True, null=True, verbose_name='sent on')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('html_body', models.TextField(verbose_name='html body')),
                ('text_body', models.TextField(blank=True, verbose_name='text body')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.Campaign', verbose_name='campaign')),
            ],
            options={
                'verbose_name_plural': 'e-mails',
                'verbose_name': 'e-mail',
                'ordering': ['-scheduled_on'],
            },
        ),
        migrations.CreateModel(
            name='MailHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=70, verbose_name='name')),
                ('value', models.TextField(validators=[django.core.validators.MaxLengthValidator(998)], verbose_name='value')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='mailing.Mail')),
            ],
            options={
                'verbose_name_plural': 'headers',
                'verbose_name': 'header',
            },
        ),
    ]
