# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignmailheader',
            options={'verbose_name': 'additional header', 'verbose_name_plural': 'additional headers'},
        ),
    ]
