# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignmailheader',
            options={'verbose_name': 'extra header', 'verbose_name_plural': 'extra headers'},
        ),
        migrations.AlterField(
            model_name='mail',
            name='html_body',
            field=models.TextField(verbose_name='HTML body'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='text_body',
            field=models.TextField(blank=True, help_text='Leave blank to generate from HTML body.', verbose_name='text body'),
        ),
    ]
