# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 17:05
from __future__ import unicode_literals

from django.db import migrations
import mailing.models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_auto_20160204_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='prefix_subject',
            field=mailing.models.VariableHelpTextBooleanField(default=True, verbose_name='prefix subject'),
        ),
    ]
