# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_auto_20160209_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignStaticAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=100, verbose_name='filename')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='mime type')),
                ('attachment', models.FilePathField(path='/home/antoine/Workspace/django-mailing/static/mailing/attachments', recursive=True, verbose_name='file')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_attachments', to='mailing.Campaign')),
            ],
            options={
                'verbose_name': 'static attachment',
                'abstract': False,
                'verbose_name_plural': 'static attachments',
            },
        ),
        migrations.CreateModel(
            name='MailDynamicAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=100, verbose_name='filename')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='mime type')),
                ('attachment', models.FileField(upload_to='mailing/attachments', verbose_name='file')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_attachments', to='mailing.Mail')),
            ],
            options={
                'verbose_name': 'dynamic attachment',
                'abstract': False,
                'verbose_name_plural': 'dynamic attachments',
            },
        ),
        migrations.CreateModel(
            name='MailStaticAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=100, verbose_name='filename')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='mime type')),
                ('attachment', models.FilePathField(path='/home/antoine/Workspace/django-mailing/static/mailing/attachments', recursive=True, verbose_name='file')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_attachments', to='mailing.Mail')),
            ],
            options={
                'verbose_name': 'static attachment',
                'abstract': False,
                'verbose_name_plural': 'static attachments',
            },
        ),
    ]
