# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 12:07
from __future__ import unicode_literals

from django.db import migrations
import mailing.models.options


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_auto_20160222_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignstaticattachment',
            name='attachment',
            field=mailing.models.options.FilePathField(recursive=True, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='mailstaticattachment',
            name='attachment',
            field=mailing.models.options.FilePathField(recursive=True, verbose_name='file'),
        ),
    ]
