# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_auto_20160226_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='e-mail')),
                ('subscribed', models.BooleanField(default=True, verbose_name='subscribed')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('subscribed_by_default', models.BooleanField(default=True, help_text='Whether potential recipients are subscribed or not to this type by default', verbose_name='subscribed by default')),
            ],
            options={
                'verbose_name': 'subscription type',
                'verbose_name_plural': 'subscription types',
            },
        ),
        migrations.AlterField(
            model_name='mail',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Sent'), (3, 'Canceled'), (4, 'Failure'), (5, 'Draft')], default=5, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', related_query_name='subscriptions', to='mailing.SubscriptionType', verbose_name='subscription type'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='subscription_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.SubscriptionType', verbose_name='subscription type'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set([('email', 'subscription_type')]),
        ),
    ]
