# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-03 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_auto_20160331_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail address')),
                ('reason', models.PositiveSmallIntegerField(choices=[(2, 'SPAM'), (3, 'Blocked'), (4, 'Hard bounce'), (1, 'Other')], default=1, verbose_name='reason')),
                ('verbose_reason', models.CharField(blank=True, max_length=250, verbose_name='verbose reason')),
                ('reported_on', models.DateTimeField(auto_now_add=True, verbose_name='reported on')),
            ],
            options={
                'ordering': ['-reported_on'],
                'verbose_name_plural': 'blacklisted addresses',
                'verbose_name': 'blacklisted address',
            },
        ),
    ]
