# Generated by Django 2.0.3 on 2018-03-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_blacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='debug_mode',
            field=models.BooleanField(default=False, verbose_name='debug mode'),
        ),
    ]
