# Generated by Django 2.0.3 on 2018-05-24 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0010_campaign_debug_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
