# Generated by Django 2.0.3 on 2018-05-30 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0011_subscription_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
